Repository gardener/gardener-discovery-server, pull requests merged in 2025-02, with the labels that each got.

#91 Serve shoot CA bundle
  charts/discovery-server/charts/application/templates/clusterrole.yaml
  cmd/discovery-server/app/app.go
  docs/api.md
  hack/ci-e2e-kind.sh
  internal/handler/certificate/handler.go
  internal/handler/certificate/handler_suite_test.go
  internal/handler/certificate/handler_test.go
  internal/handler/handler.go
  internal/handler/handler_test.go
  internal/handler/openidmeta/handler.go
  internal/handler/openidmeta/handler_test.go
  internal/reconciler/certificate/add.go
  internal/reconciler/certificate/certificate_suite_test.go
  internal/reconciler/certificate/reconciler.go
  internal/reconciler/certificate/reconciler_test.go
  internal/reconciler/openidmeta/metadata_test.go
  internal/store/certificate/data.go
  skaffold.yaml
  test/e2e/common_test.go
  test/e2e/create_enable_delete_test.go
Labels: kind/enhancement, cla: yes, lgtm, approved, size/XXL

#97 Fix concurrent access to map
  internal/reconciler/certificate/reconciler.go
Labels: kind/bug, size/XS, cla: yes, lgtm, approved

#98 Update go to 1.23.6 in the verify step
  .ci/pipeline_definitions
Labels: kind/enhancement, size/XS, cla: yes, lgtm, approved
